name = "trending-temps"
type = "webpack"
account_id = "661484bfa811d50ad0a7c946485ad9ae"
zone_id = "3bd9290f20643845d27b837bf90597ff"
workers_dev = false
route = "trendingtemps.com/*"

[site]
bucket = "./build"
entry-point = "workers-site"
